name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create config file with API key
      run: |
        echo "window.CONFIG = { GOOGLE_API_KEY: '${{ secrets.GOOGLE_API_KEY }}' };" > config.js
    
    - name: Copy files to dist
      run: |
        mkdir -p dist
        cp index.html dist/
        cp styles.css dist/
        cp letterGenerator.js dist/
        cp config.js dist/
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist